
export const GET_ALL_CARDS_SUCCESS = 'GET_ALL_CARDS_SUCCESS';
export const GET_ALL_CARDS_FAILURE = 'GET_ALL_CARDS_FAILURE';

export const SET_CARD_SUCCESS = 'SET_CARD_SUCCESS';
export const SET_CARD_FAILURE = 'SET_CARD_FAILURE';